--Exercice 1
--Q1
CREATE TABLE JEU(
    ID INT,
    NOM TEXT,
    CONSTRAINT PK_JEU_ID PRIMARY KEY(ID));

INSERT INTO JEU VALUES(1, 'Minecraft');
INSERT INTO JEU VALUES(2, 'Mario');
INSERT INTO JEU VALUES(3, 'Metroid');

SELECT * FROM JEU;

CREATE TABLE SCORES(
    LOGIN TEXT NOT NULL,
    ID INT,
    SCORE INT,
    CONSTRAINT FK_ID FOREIGN KEY(ID) REFERENCES JEU(ID));

INSERT INTO SCORES VALUES('Le Génial', 1, 2000);
INSERT INTO SCORES VALUES('Luigi', 2, 3000);
INSERT INTO SCORES VALUES('KRaid', 3, 6000);
INSERT INTO SCORES VALUES('Le Génial', 1, 3000);
INSERT INTO SCORES VALUES('Luigi', 2, 4000);
INSERT INTO SCORES VALUES('KRaid', 3, 7000);
INSERT INTO SCORES VALUES('Le Génial', 2, 2000);
INSERT INTO SCORES VALUES('Luigi', 3, 3000);
INSERT INTO SCORES VALUES('KRaid', 1, 6000);

SELECT * FROM SCORES;

CREATE VIEW messcores
    AS SELECT LOGIN, NOM, SCORE
    FROM JEU INNER JOIN SCORES ON JEU.ID=SCORES.ID
    ORDER BY LOGIN, NOM, SCORE ASC;

SELECT * FROM messcores;

CREATE VIEW maximus
    AS SELECT LOGIN, NOM, MAX(SCORE) as maxSC
    FROM messcores
    GROUP BY LOGIN, NOM
    ORDER BY LOGIN, NOM ASC;
    
SELECT NOM, Max(maxSC)
    FROM maximus
    GROUP BY NOM;
